# Generated by Django 4.2.1 on 2023-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
